### ISSUE TITLE
K8s 1.22+

### ISSUE THREAD

**Issue by dimm0** [admiraltyio/admiralty#130]
Are we 1.22 compatible? Controller is crashlooping...

```
I1221 06:47:46.404550       1 request.go:621] Throttling request took 11.280249309s, request: GET:https://10.96.0.1:443/apis/upload.cdi.kubevirt.io/v1beta1?timeout=32s
I1221 06:47:48.423850       1 leaderelection.go:242] attempting to acquire leader lease  admiralty/admiralty-controller-manager...
panic: the server could not find the requested resource

goroutine 783 [running]:
k8s.io/apimachinery/pkg/util/runtime.Must(...)
    k8s.io/apimachinery@v0.18.9/pkg/util/runtime/runtime.go:171
main.startVirtualKubeletServers(0x1929690, 0xc0002fe840, 0xc0000282a0, 0x3, 0x4, 0x1946928, 0xc00059dce0)
    admiralty.io/multicluster-scheduler/cmd/agent/main.go:312 +0x6cf
created by main.main
    admiralty.io/multicluster-scheduler/cmd/agent/main.go:83 +0x219
```

**Comment by adrienjt** [comment]
Support for K8s 1.22 is planned for January.
